# configurações do site
title: gawiga
description: um blog, um site, uma parte de mim, na internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://gawiga.com/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
enforce_ssl: gawiga.com

# configurações do usuário
username: Gawiga
# user_description: desenvolvedor
# user_title: developer
email: contato@gawiga.com
twitter_username: gawiga
github_username:  gawiga
facebook_username:  gawiga
disqus_username: gawiga
idade: 26
nome: Gabriel W. Galdino
version: 0.2.0

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navig ation
# For external links add external: true
links:
  - title: Início
    url: /
  - title: Blog
    url: /blog
  - title: Experimentos
    url: /backdoor

# Translate
pt:
  sobremim: Sobre mim 
  sobre: sobre
  postagens: postagens
  contato: contato
  servicos: serviços
  descricao: desenvolvedor
  pesquisar: pesquisar
en:
  sobre: about
  sobremim: About me
  postagens: posts
  contato: contact
  servicos: services
  descricao: developer
  pesquisar: search

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']