# configurações do site
title: Gawiga
description: A personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gawiga.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# configurações do usuário
username: Gawiga
user_description: Gawiga Developer 
user_title: Gawiga Developer
email: gawiga@gmail.com
twitter_username: gawiga
github_username:  gawiga
gplus_username:  gawiga
disqus_username: gawiga

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
